services:
    instance:
        build: .
        image: gqngster/btw-server
        container_name: btw-server
        user: "1000:1000"
        ports:
            - "25565:25565"
        volumes:
            - world:/opt/server/world
            - data:/opt/server/data
        restart: unless-stopped
        stdin_open: true
        tty: true

volumes:
    data: {}
    world: {}
